name: form_validator
description: A lightweight and composable Flutter form validation package with built-in validators for email, phone, password, regex, and more.
version: 0.0.1
topics:
  - flutter
  - forms
  - validation
  - utilities

environment:
  sdk: ^3.11.0

dependencies: {}

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
